versions:
    - 1.8.6-p420
    - 1.8.7-p374
    - 1.9.1-p431
    - 1.9.2-p320
    - 1.9.3
    - 2.0.0-p481
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.1.6
    - 2.1.7
    - 2.1.8
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
    - 2.2.4
    - 2.3.0

empty_version:
    version: ~
    default: 0
    bundler: 0
    gems: []
